//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTranProj.sqlwebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContextVO", Namespace="http://silvercloudsolutions.net/")]
    [System.SerializableAttribute()]
    public partial class ContextVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dbServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dbNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string dbServer {
            get {
                return this.dbServerField;
            }
            set {
                if ((object.ReferenceEquals(this.dbServerField, value) != true)) {
                    this.dbServerField = value;
                    this.RaisePropertyChanged("dbServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dbName {
            get {
                return this.dbNameField;
            }
            set {
                if ((object.ReferenceEquals(this.dbNameField, value) != true)) {
                    this.dbNameField = value;
                    this.RaisePropertyChanged("dbName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userID {
            get {
                return this.userIDField;
            }
            set {
                if ((object.ReferenceEquals(this.userIDField, value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sql_WebService_Content", Namespace="http://silvercloudsolutions.net/")]
    [System.SerializableAttribute()]
    public partial class Sql_WebService_Content : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopTranProj.sqlwebservice.Sql_WebService[] obj_Sql_ServiceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ShopTranProj.sqlwebservice.Sql_WebService[] obj_Sql_Service {
            get {
                return this.obj_Sql_ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.obj_Sql_ServiceField, value) != true)) {
                    this.obj_Sql_ServiceField = value;
                    this.RaisePropertyChanged("obj_Sql_Service");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sql_WebService", Namespace="http://silvercloudsolutions.net/")]
    [System.SerializableAttribute()]
    public partial class Sql_WebService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string execStringField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string execString {
            get {
                return this.execStringField;
            }
            set {
                if ((object.ReferenceEquals(this.execStringField, value) != true)) {
                    this.execStringField = value;
                    this.RaisePropertyChanged("execString");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sql_WebService_Response", Namespace="http://silvercloudsolutions.net/")]
    [System.SerializableAttribute()]
    public partial class Sql_WebService_Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arr_resultListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ShopTranProj.sqlwebservice.ErrorVO[] errorListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string methodField;
        
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string arr_resultList {
            get {
                return this.arr_resultListField;
            }
            set {
                if ((object.ReferenceEquals(this.arr_resultListField, value) != true)) {
                    this.arr_resultListField = value;
                    this.RaisePropertyChanged("arr_resultList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ShopTranProj.sqlwebservice.ErrorVO[] errorList {
            get {
                return this.errorListField;
            }
            set {
                if ((object.ReferenceEquals(this.errorListField, value) != true)) {
                    this.errorListField = value;
                    this.RaisePropertyChanged("errorList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string method {
            get {
                return this.methodField;
            }
            set {
                if ((object.ReferenceEquals(this.methodField, value) != true)) {
                    this.methodField = value;
                    this.RaisePropertyChanged("method");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorVO", Namespace="http://silvercloudsolutions.net/")]
    [System.SerializableAttribute()]
    public partial class ErrorVO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorDescriptionField;
        
        private int instanceNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string errorID {
            get {
                return this.errorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.errorIDField, value) != true)) {
                    this.errorIDField = value;
                    this.RaisePropertyChanged("errorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.errorDescriptionField, value) != true)) {
                    this.errorDescriptionField = value;
                    this.RaisePropertyChanged("errorDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int instanceNo {
            get {
                return this.instanceNoField;
            }
            set {
                if ((this.instanceNoField.Equals(value) != true)) {
                    this.instanceNoField = value;
                    this.RaisePropertyChanged("instanceNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://silvercloudsolutions.net/", ConfigurationName="sqlwebservice.SqlWebServicesSoap")]
    public interface SqlWebServicesSoap {
        
        // CODEGEN: Generating message contract since element name objUserContext from namespace http://silvercloudsolutions.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://silvercloudsolutions.net/Sql_Service", ReplyAction="*")]
        ShopTranProj.sqlwebservice.Sql_ServiceResponse Sql_Service(ShopTranProj.sqlwebservice.Sql_ServiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://silvercloudsolutions.net/Sql_Service", ReplyAction="*")]
        System.Threading.Tasks.Task<ShopTranProj.sqlwebservice.Sql_ServiceResponse> Sql_ServiceAsync(ShopTranProj.sqlwebservice.Sql_ServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sql_ServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sql_Service", Namespace="http://silvercloudsolutions.net/", Order=0)]
        public ShopTranProj.sqlwebservice.Sql_ServiceRequestBody Body;
        
        public Sql_ServiceRequest() {
        }
        
        public Sql_ServiceRequest(ShopTranProj.sqlwebservice.Sql_ServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://silvercloudsolutions.net/")]
    public partial class Sql_ServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ShopTranProj.sqlwebservice.ContextVO objUserContext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string securityToken;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ShopTranProj.sqlwebservice.Sql_WebService_Content dbdataIn;
        
        public Sql_ServiceRequestBody() {
        }
        
        public Sql_ServiceRequestBody(ShopTranProj.sqlwebservice.ContextVO objUserContext, string securityToken, ShopTranProj.sqlwebservice.Sql_WebService_Content dbdataIn) {
            this.objUserContext = objUserContext;
            this.securityToken = securityToken;
            this.dbdataIn = dbdataIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Sql_ServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Sql_ServiceResponse", Namespace="http://silvercloudsolutions.net/", Order=0)]
        public ShopTranProj.sqlwebservice.Sql_ServiceResponseBody Body;
        
        public Sql_ServiceResponse() {
        }
        
        public Sql_ServiceResponse(ShopTranProj.sqlwebservice.Sql_ServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://silvercloudsolutions.net/")]
    public partial class Sql_ServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ShopTranProj.sqlwebservice.Sql_WebService_Response Sql_ServiceResult;
        
        public Sql_ServiceResponseBody() {
        }
        
        public Sql_ServiceResponseBody(ShopTranProj.sqlwebservice.Sql_WebService_Response Sql_ServiceResult) {
            this.Sql_ServiceResult = Sql_ServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SqlWebServicesSoapChannel : ShopTranProj.sqlwebservice.SqlWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SqlWebServicesSoapClient : System.ServiceModel.ClientBase<ShopTranProj.sqlwebservice.SqlWebServicesSoap>, ShopTranProj.sqlwebservice.SqlWebServicesSoap {
        
        public SqlWebServicesSoapClient() {
        }
        
        public SqlWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SqlWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ShopTranProj.sqlwebservice.Sql_ServiceResponse ShopTranProj.sqlwebservice.SqlWebServicesSoap.Sql_Service(ShopTranProj.sqlwebservice.Sql_ServiceRequest request) {
            return base.Channel.Sql_Service(request);
        }
        
        public ShopTranProj.sqlwebservice.Sql_WebService_Response Sql_Service(ShopTranProj.sqlwebservice.ContextVO objUserContext, string securityToken, ShopTranProj.sqlwebservice.Sql_WebService_Content dbdataIn) {
            ShopTranProj.sqlwebservice.Sql_ServiceRequest inValue = new ShopTranProj.sqlwebservice.Sql_ServiceRequest();
            inValue.Body = new ShopTranProj.sqlwebservice.Sql_ServiceRequestBody();
            inValue.Body.objUserContext = objUserContext;
            inValue.Body.securityToken = securityToken;
            inValue.Body.dbdataIn = dbdataIn;
            ShopTranProj.sqlwebservice.Sql_ServiceResponse retVal = ((ShopTranProj.sqlwebservice.SqlWebServicesSoap)(this)).Sql_Service(inValue);
            return retVal.Body.Sql_ServiceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShopTranProj.sqlwebservice.Sql_ServiceResponse> ShopTranProj.sqlwebservice.SqlWebServicesSoap.Sql_ServiceAsync(ShopTranProj.sqlwebservice.Sql_ServiceRequest request) {
            return base.Channel.Sql_ServiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ShopTranProj.sqlwebservice.Sql_ServiceResponse> Sql_ServiceAsync(ShopTranProj.sqlwebservice.ContextVO objUserContext, string securityToken, ShopTranProj.sqlwebservice.Sql_WebService_Content dbdataIn) {
            ShopTranProj.sqlwebservice.Sql_ServiceRequest inValue = new ShopTranProj.sqlwebservice.Sql_ServiceRequest();
            inValue.Body = new ShopTranProj.sqlwebservice.Sql_ServiceRequestBody();
            inValue.Body.objUserContext = objUserContext;
            inValue.Body.securityToken = securityToken;
            inValue.Body.dbdataIn = dbdataIn;
            return ((ShopTranProj.sqlwebservice.SqlWebServicesSoap)(this)).Sql_ServiceAsync(inValue);
        }
    }
}
